version: "3.3"

services:
  tg-file-url:
    image: pixia1234/tg-file-url:latest
    container_name: tg-file-url
    restart: unless-stopped
    env_file:
      - ./compose.env
    volumes:
      - ./data:/app/data
    ports:
      - "8080:8080"
